[appendix]
:appendix-caption: Annex
== Conformance Class Abstract Test Suite (Normative)

[NOTE]
Ensure that there is a conformance class for each requirements class and a test for each requirement (identified by requirement name and number)

This section contains the conformance classes for the SensorThings API Read (Core). The SensorThings API service needs to pass all the conformance tests defined in this section.

=== Conformance Class: Fugitive Emissions Management SensorThings API Thing Entity

[width="100%",cols="25%,19%,56%",options="header",]
|===
|*Conformance Class* |*/conf/thing* |
|Requirements |
req/thing/thing-entity

req/thing/thing-relations

|
|Dependency | http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/thing[http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/thing] |
|*Test* |/conf/thing |
| |Requirement a|
req/thing/thing-entity,

req/thing/relations.

| |Test purpose |Verify that the Thing entity has the mandatory properties and mandatory relations as defined in Fugitive Emissions Management SensorThings API Specification.
| |Test method a|
Inspect the full JSON object of the Thing entity sets to identify, if each entity has the mandatory properties defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

Inspect the full JSON object of each Thing entity sets to identify, if each entity has the mandatory relations defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

| |Test type |Validation
|===

=== Conformance Class: Fugitive Emissions Management SensorThings API Location Entity

|===
|*Conformance Class*| */conf/location* |

|Requirements |
req/location/location-entity

req/location/location-relations
|
|Dependency | http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/location[http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/location] |
|*Test* |/conf/location |
| | Requirement a|
req/location/location-entity,

req/location/location-relations.

| |Test purpose |Verify that the Location entity has the mandatory properties and mandatory relations as defined in Fugitive Emissions Management SensorThings API Specification.
| |Test method a|
Inspect the full JSON object of the Location entity sets to identify, if each entity has the mandatory properties defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

Inspect the full JSON object of each Location entity sets to identify, if each entity has the mandatory relations defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

| |Test type | Validation
|===

=== Conformance Class: Fugitive Emissions Management SensorThings API Datastream Entity

|===
|*Conformance Class*| */conf/datastream* |

|Requirements |
/req/datastream/number-of-fugitive-emissions-entity

/req/datastream/number-of-fugitive-emissions-relation,

/req/datastream/fugitive-emissions-volume-entity,

/req/datastream/fugitive-emissions-volume-relation,

/req/datastream/fugitive-emissions-mass-entity,

/req/datastream/fugitive-emissions-mass-relation.
|
|Dependency | http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/datastream[http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/datastream] |
|*Test* |/conf/datastream |
| | Requirement a|
/req/datastream/number-of-fugitive-emissions-entity,

/req/datastream/number-of-fugitive-emissions-relation,

/req/datastream/fugitive-emissions-volume-entity,

/req/datastream/fugitive-emissions-volume-relation,

/req/datastream/fugitive-emissions-mass-entity,

/req/datastream/fugitive-emissions-mass-relation.

| |Test purpose |Verify that each Datastream entity has the mandatory properties and mandatory relations as defined in Fugitive Emissions Management SensorThings API Specification.
| |Test method a|
Inspect the full JSON object of the Datastream entity sets to identify, if each entity has the mandatory properties defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

Inspect the full JSON object of each Datastream entity sets to identify, if each entity has the mandatory relations defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

| |Test type | Validation
|===

=== Conformance Class: Fugitive Emissions Management SensorThings API ObservedProperty Entity

[width="100%",cols="25%,19%,56%",options="header",]
|===
|*Conformance Class* |*/conf/observed-property* |
|Requirements |
req/observed-property/number-of-fugitive-emissions-entity,

req/observed-property/number-of-fugitive-emissions-relations.

|
|Dependency | http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/observed-property[http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/observed-property] |
|*Test* |/conf/observed-property |
| |Requirement a|
req/observed-property/number-of-fugitive-emissions-entity,

req/observed-property/number-of-fugitive-emissions-relations.

| |Test purpose |Verify that the ObservedProperty entity has the mandatory properties and mandatory relation as defined in Fugitive Emissions Management SensorThings API Specification.
| |Test method a|
Inspect the full JSON object of the ObservedProperty entity sets to identify, if each entity has the mandatory properties defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

Inspect the full JSON object of each ObservedProperty entity sets to identify, if each entity has the mandatory relations defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

| |Test type |Validation
|===

=== Conformance Class: Fugitive Emissions Management SensorThings API Observation Entity

[width="100%",cols="25%,19%,56%",options="header",]
|===
|*Conformance Class* |*/conf/observation* |
|Requirements |
req/observation/observation-entity,

req/observation/observation-relations.

|
|Dependency | http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/observation[http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/observation] |
|*Test* |/conf/observation |
| |Requirement a|
req/observation/observation-entity,

req/observation/observation-relations.

| |Test purpose |Verify that the Observation entity has the mandatory properties and mandatory relation as defined in Fugitive Emissions Management SensorThings API Specification.
| |Test method a|
Inspect the full JSON object of the Observation entity sets to identify, if each entity has the mandatory properties defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

Inspect the full JSON object of each Observation entity sets to identify, if each entity has the mandatory relations defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

| |Test type |Validation
|===

=== Conformance Class: Fugitive Emissions Management SensorThings API FeatureOfInterest Entity

[width="100%",cols="25%,19%,56%",options="header",]
|===
|*Conformance Class* |*/conf/feature-of-interest* |
|Requirements |
req/feature-of-interest/feature-of-interest-entity,

req/feature-of-interest/feature-of-interest-relations.

|
|Dependency | http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/feature-of-interest[http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/feature-of-interest] |
|*Test* |/conf/feature-of-interest |
| |Requirement a|
req/feature-of-interest/feature-of-interest-entity,

req/feature-of-interest/feature-of-interest-relations.

| |Test purpose |Verify that the FeatureOfInterest entity has the mandatory properties and mandatory relation as defined in Fugitive Emissions Management SensorThings API Specification.
| |Test method a|
Inspect the full JSON object of the FeatureOfInterest entity sets to identify, if each entity has the mandatory properties defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

Inspect the full JSON object of each FeatureOfInterest entity sets to identify, if each entity has the mandatory relations defined in the corresponding requirement. Pass if no errors reported. Fail otherwise.

| |Test type |Validation
|===
