== Conformance
This OGC Best Practice (OGC BP) defines a SensorThings API for fugitive methane emissions management based on the Alberta Energy Regulator’s regulatory requirement for fugitive emissions management https://www.aer.ca/regulating-development/rules-and-directives/directives/directive-060[AER Directive 60 (2021)].

Conformance with this OGC BP shall be checked using all the relevant tests specified in annex a (normative) of this document.

All requirement classes and conformance classes described in this document are owned by the document(s) identified.

The following table lists the requirement classes defined in this OGC BP.

[NOTE]
The text in the _Requirements class id_ and _Requirements_ columns in the following table is the path fragment that,
when appended to the URI: http://www.opengis.net/spec/imsw-fm-aer60/1.0, provides the URI that
can be used to unambiguously identify the requirement and the conformance class.

[cols="a,a,a"width="90%",options="header"]
|===
|Requirements class id |Requirements |Description
|/req/datamodel/thing |
* /req/datamodel/thing/properties
* /req/datamodel/thing/relations |Thing entity

|/req/datamodel/location |
* /req/datamodel/location/properties
* /req/datamodel/location/relations |Location entity

|/req/datamodel/datastream |
* /req/datamodel/datastream/number-of-fugitive-emissions-properties
* /req/datamodel/datastream/number-of-fugitive-emissions-relations
* /req/datamodel/datastream/fugitive-emissions-volume-properties
* /req/datamodel/datastream/fugitive-emissions-volume-relations
* /req/datamodel/datastream/fugitive-emissions-mass-properties
* /req/datamodel/datastream/fugitive-emissions-mass-relations |Datastream entity

|/req/datamodel/observed-property |
* /req/datamodel/observed-property/properties |ObservedProperty entity

|/req/datamodel/observation |
* /req/datamodel/observation/properties |Observation entity

|/req/datamodel/feature-of-interest |

* /req/datamodel/feature-of-interest/properties |FeatureOfInterest entity

|/req/datamodel/sensor |
* /req/datamodel/sensor/properties |Sensor entity

|===
