== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Best Practice.

For the purposes of this document, the following additional terms and definitions apply.

=== Symbols (and abbreviated terms)

==== *API*
Application Programming Interface

==== *URI*
Uniform Resource Identifier

==== *AER*
Alberta Energy Regulator

==== *ATS*
Alberta Township Survey

==== *LSD*
Legal Subdivisions

==== *IANA*
Internet Assigned Numbers Authority

==== *JSON*
JavaScript Object Notation

==== *ID*
Identity Document

==== *OGC*
Open Geospatial Consortium

==== *GeoJSON*
Geographic JSON

==== *FEMP*
Fugitive Emissions Management Program

==== *FEM-STA*
Fugitive Emissions Management - SensorThings API

==== *STA*
SensorThings API
