== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Best Practice.

For the purposes of this document, the following additional terms and definitions apply.

=== Abbreviations

*AER*   Alberta Energy Regulator

*API*   Application Programming Interface

*ATS*   Alberta Township Survey

*FEM-STA*   Fugitive Emissions Management - SensorThings API

*FEMP*   Fugitive Emissions Management Program

*GeoJSON*   Geographic JSON

*IANA*   Internet Assigned Numbers Authority

*ID*   Identity Document

*JSON*   JavaScript Object Notation

*LSD*   Legal Subdivisions

*OGC*   Open Geospatial Consortium

*STA*   SensorThings API

*URI*   Uniform Resource Identifier

*OGI*   Optical Gas Imaging

*SWE*   Sensor Web Enablement

*BP*   Best Practice
