== Conformance
This Best Practice defines XXXX.

Conformance with this Best Practice shall be checked using all the relevant tests specified in annex a (normative) of this document.

All requirement classes and conformance classes described in this document are owned by the document(s) identified.

The following table lists the requirement classes defined in this Best Practice.

[NOTE]
The text in the _Requirements class id_ and _Requirements_ columns in the following table is the path fragment that,
when appended to the URI: http://www.opengis.net/spec/sensorthings-fugitive-emissions-ab/1.0, provides the URI that
can be used to unambiguously identify the requirement and the conformance class.

[cols="a,a,a"width="90%",options="header"]
|===
|Requirements class id |Requirements |Description
|/req/datamodel/thing |
* /req/datamodel/thing/thing-entity
* /req/datamodel/thing/thing-relations |Thing entity

|/req/datamodel/location |
* /req/datamodel/location/location-entity
* /req/datamodel/location/location-relations |Location entity

|/req/datamodel/datastream |
* /req/datamodel/datastream/number-of-fugitive-emissions-entity
* /req/datamodel/datastream/number-of-fugitive-emissions-relations
* /req/datamodel/datastream/fugitive-emissions-volume-entity
* /req/datamodel/datastream/fugitive-emissions-volume-relations
* /req/datamodel/datastream/fugitive-emissions-mass-entity
* /req/datamodel/datastream/fugitive-emissions-mass-relations |Datastream entity

|/req/datamodel/observed-property |
* /req/datamodel/observed-property/number-of-fugitive-emissions-entity |ObservedProperty entity

|/req/datamodel/observation |
* /req/datamodel/observation/observation-entity |Observation entity

|/req/datamodel/feature-of-interest |
* /req/datamodel/feature-of-interest/feature-of-interest-entity
* /req/datamodel/feature-of-interest/feature-of-interest-relations |FeatureOfInterest entity

|/req/datamodel/sensor |
* /req/datamodel/sensor/sensor-entity |Sensor Entity

|===
