== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this Best Practice.

For the purposes of this document, the following additional terms and definitions apply.

*Facility ID*

  A unique facility identification code, with 4 letters and 7 numbers (e.g., ABWP1234567), assigned by Petrinex to each facility [AER Directive 60 (2021)].

*Fugitive Emissions*

  Unintentional releases of hydrocarbons to the atmosphere [AER Directive 60 (2021)].

*Fugitive Emissions Screenings*

  Site-wide evaluations where the primary purpose is to identify fugitive emissions (e.g., from open thief hatches). These are less comprehensive than fugitive emission surveys [AER Directive 60 (2021)].

*Fugitive Emission Surveys*

  Site-wide evaluations that use equipment-based methods to detect and identify sources of fugitive emissions for repair. These surveys are considered comprehensive evaluations that can assist in reducing both small volumes and large volumes of fugitive emissions [AER Directive 60 (2021)].

*Petrinex*

  Canada’s Petroleum Information Network

*Site*

  The area defined by the boundaries of a surface lease for upstream oil and gas facilities and wells (pads counted as one lease) [AER Directive 60 (2021)].

*Leak*

  A release of hydrocarbons from an equipment component is a leak if [Regulations Respecting Reduction in the Release of Methane and Certain Volatile Organic Compounds (2018)]
  * the release consists of at least 500 ppmv of hydrocarbons, as determined by an inspection conducted by means of an eligible portable monitoring instrument in accordance with EPA Method 21; or
  * the release is detected
  ** during an inspection conducted by means of an eligible optical gas-imaging instrument, or
  ** by means of an auditory method, an olfactory method or a visual method, including the observation of the dripping of hydrocarbon liquids from the equipment component.

*Local Regulation*

  The federal regulations that apply to methane in the upstream oil and gas sector aim to control methane emissions and also reduce the amount of volatile organic compounds (VOCs) released into the air
  [Canada's methane regulations (2018)].

*Fugitive Emissions Management Program*

  A plan and supporting systems to systematically detect and manage fugitive emissions.
  Fugitive Emissions Management Programs are intended to complement a duty holder's overall emissions reduction strategy [AER Directive 60 (2021)].

*Vent Emission*

    The intentional controlled release of un-combusted gases directly to the atmosphere [Oil and Gas Glossary and Definitions (2020)].
