[big]*i.     Abstract*

<Insert Abstract Text here>

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document,  sensor web, methane emissions, Internet of Things, SensorThings, climate change

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

SensorUp Inc., the University of Calgary, TC Energy, Fraunhofer IOSB

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

[width="90%",options="header"]
|===
|Name |Affliation
|Steve Liang |SensorUp Inc./University of Calgary
|John Tang |TC Energy
|Patrick Kelly |TC Energy
|Sara Saeedi |University of Calgary
|Sina Kiaei |University of Calgary
|Hylke van der Schaaf |Fraunhofer IOSB
|===


The editor would like to acknowledge that this work is the result of collaboration and review of many organizations and would like to thank for the comments and contributions from:

* GeoConnections, Natural Resources Canada
* Cenovus Energy
* Canadian Natural Resources (CNRL)
* Alberta Innovates

Note: this does not imply a complete endorsement by these organizations.
